### PR TITLE
RTXteam/RTX#1751, update python install script to add deadsnakes repo

### PR DESCRIPTION
**Pull request by finnagin**
This will allow ubuntu20.04 to install python3.7

### CODE REVIEW

**Comment by finnagin** [comment]
@saramsey Whenever you get a chance could you approve this? Apparently I don't have permission to commit directly to the RTX-KG2 repo.

**Comment by saramsey** [comment]
Thanks, just sent you invite for write access to the RTX-KG2 repo.

**Comment by saramsey** [comment]
I have merged. Testing now....

**Comment by saramsey** [comment]
this patch needed a tweak for some stuff downstream in the script because the `.deb` filename changed in Ubuntu 20. See issue #186.

**Pull request merged**
